name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: install build tools
      run: |
        sudo apt -y update
        sudo apt -y install ninja-build clang
    - name: build_gcc
      run: |
        export CC=/usr/bin/gcc
        export CXX=/usr/bin/g++
        cd build_gcc
        cmake -GNinja ..
        ninja
    - name: test_gcc
      run: |
        cd build_gcc
        ./main
    - name: build_clang
      run: |
        which clang
        which clang++
