name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: install build tools
      run: |
        sudo apt -y update
        sudo apt -y install ninja-build clang
    - name: build_gcc
      run: |
        export CC=$(which gcc)
        export CXX=$(which g++)
        mkdir build_gcc
        cd build_gcc
        cmake -GNinja ..
        ninja
    - name: test_gcc
      run: |
        cd build_gcc
        ./main
    - name: build_clang
      run: |
        export CC=$(which clang)
        export CXX=$(which clang++)
        mkdir build_clang
        cd build_clang
        cmake -GNinja ..
        ninja
    - name: test_clang
      run: |
        cd build_clang
        ./main
