name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: install build tools
      run: |
        sudo apt -y update
        sudo apt -y install ninja-build clang
    - name: build
      run: |
        cd build
        cmake -GNinja ..
        ninja
    - name: test
      run: |
        cd build
        ./main
